### ISSUE TITLE
Incorrect display of dates

### ISSUE THREAD

**Issue by Ravicenite** [getglimpses/community#8]
**Describe the bug**
The dates in the calendar tab are displayed incorrectly. All have shifted one day forward. The 1st of October 2019 was on a Tuesday, however, in Glimpses it is shown as a Wednesday. This shift persists throughout the calendar (and nowhere else, the days and dates on the entries themselves are correct).

**Expected behaviour**
Correct display of the dates in the calendar.

**Screenshots**
![image](https://user-images.githubusercontent.com/57096070/67675854-84c2cd80-f980-11e9-97d3-713e7734f8cd.png)

**Comment by getglimpses** [comment]
@Ravicenite, Thanks for raising the bug here.  "I have just released a new update of glimpses addressing this "date jumping ahead issue." #version: 0.16.0.25779

![image](https://user-images.githubusercontent.com/41840090/67677341-3a037e80-f99d-11e9-973a-26f7db5c0b4a.png)

**Comment by Ravicenite** [comment]
@getglimpses How do I update Glimpses?

**Comment by getglimpses** [comment]
> @getglimpses How do I update Glimpses
All glimpses updates are automatic. 
if updates are downloaded at your end, it will be applied once you **restart** the glimpses program.

1>
You can navigate to below path and confirm if the latest version are downloaded.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/41840090/67685345-cfe2dd80-f98c-11e9-9ef2-ab7aeac5d71d.png">

2>
Or you can directly download the latest glimpses installer from the e-mail (you received after the stripe payment) and do manual install.

<img width="933" alt="glimpses-email" src="https://user-images.githubusercontent.com/41840090/67685679-7202c580-f98d-11e9-9cda-c17c9fcf35e7.png">
And you can confirm the version @ glimpses About Window.

Pls let me know if you have any other queries.

Thanks,
AA

**Comment by Ravicenite** [comment]
Dear AA,

I seem to have the latest version, but the issue regarding the display of dates still occurs.

![image](https://user-images.githubusercontent.com/57096070/67687201-40432c00-f998-11e9-8e97-d4b9d1ab219e.png)

**Comment by getglimpses** [comment]
OMG, I have re-opened the issue, let me investigate. I will revert you asap.

**Comment by getglimpses** [comment]
@Ravicenite My bad, I mistook you issue as timezone issue. 
Have fixed the same & released a new version v0.17.0.34334.
I'd appreciate if you could please confirm the fix at your end. Then you we can close this issue.
Thanks a ton for your patience.

**Comment by Ravicenite** [comment]
Thank you very much! The problem is all fixed now!

![image](https://user-images.githubusercontent.com/57096070/67691711-52749880-f99f-11e9-9fa7-9d7f1c2df45f.png)

**Comment by getglimpses** [comment]
:raised_hands:
